import { UserProfile, SocioSolicitud, NovedadInstitucional } from '@/types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-admin-01',
    email: 'admin@bibliotecaroncedo.ar',
    role: 'admin',
    nombre: 'Lautaro',
    apellido: 'Administración',
    dni: '28.450.120',
    fecha_nacimiento: '1978-05-10',
    sexo: 'Hombre',
    telefono: '+54 9 358 412-3456',
    whatsapp_codigo: '+54',
    whatsapp: '93584123456',
    pais: 'Argentina',
    provincia: 'Córdoba',
    localidad: 'Alcira Gigena',
    barrio: 'Centro',
    calle: 'Belgrano',
    numero: '450',
    domicilio: 'Belgrano 450',
    observaciones: 'Administrador general del sistema.',
    avatar_url: '',
    numero_socio: '0001',
    categoria_socio: 'Honorario',
    fecha_alta_socio: '1995-03-15',
    estado_cuota: 'al_dia',
    created_at: '2020-01-01T00:00:00Z',
  },
  {
    id: 'user-socio-01',
    email: 'socio@bibliotecaroncedo.ar',
    role: 'socio',
    nombre: 'Pedro',
    apellido: 'González',
    dni: '34.892.110',
    fecha_nacimiento: '1989-06-22',
    sexo: 'Hombre',
    telefono: '+54 9 358 520-8911',
    whatsapp_codigo: '+54',
    whatsapp: '93585208911',
    pais: 'Argentina',
    provincia: 'Córdoba',
    localidad: 'Alcira Gigena',
    barrio: 'Barrio Norte',
    calle: 'San Martín',
    numero: '672',
    domicilio: 'San Martín 672',
    observaciones: 'Socio activo desde 2021.',
    avatar_url: '',
    numero_socio: '1042',
    categoria_socio: 'Activo',
    fecha_alta_socio: '2021-04-10',
    estado_cuota: 'al_dia',
    created_at: '2021-04-01T00:00:00Z',
  },
  {
    id: 'user-nuevo-01',
    email: 'usuario@bibliotecaroncedo.ar',
    role: 'usuario',
    nombre: 'María Elena',
    apellido: 'Gómez',
    dni: '41.302.981',
    fecha_nacimiento: '1998-11-14',
    sexo: 'Mujer',
    telefono: '+54 9 358 488-7722',
    whatsapp_codigo: '+54',
    whatsapp: '93584887722',
    pais: 'Argentina',
    provincia: 'Córdoba',
    localidad: 'Alcira Gigena',
    barrio: 'San Vicente',
    calle: 'Córdoba',
    numero: '128',
    domicilio: 'Córdoba 128',
    observaciones: 'Interesada en talleres literarios y novelas históricas.',
    avatar_url: '',
    created_at: '2026-03-15T00:00:00Z',
  },
];

export const INITIAL_SOLICITUDES: SocioSolicitud[] = [
  {
    id: 'sol-001',
    user_id: 'user-nuevo-01',
    nombre: 'María Elena',
    apellido: 'Gómez',
    email: 'usuario@bibliotecaroncedo.ar',
    dni: '41.302.981',
    telefono: '+54 9 358 488-7722',
    domicilio: 'Córdoba 128',
    localidad: 'Alcira Gigena',
    fecha_nacimiento: '1998-11-14',
    categoria_solicitada: 'Activo',
    estado: 'pendiente',
    fecha_solicitud: '2026-04-02T14:30:00Z',
  },
  {
    id: 'sol-002',
    user_id: 'user-socio-01',
    nombre: 'Pedro',
    apellido: 'González',
    email: 'socio@bibliotecaroncedo.ar',
    dni: '34.892.110',
    telefono: '+54 9 358 520-8911',
    domicilio: 'San Martín 672',
    localidad: 'Alcira Gigena',
    fecha_nacimiento: '1989-06-22',
    categoria_solicitada: 'Activo',
    estado: 'aprobada',
    fecha_solicitud: '2021-04-05T10:00:00Z',
    fecha_resolucion: '2021-04-10T11:20:00Z',
    notas_admin: 'Aprobado en reunión de comisión directiva.',
  },
];

export const NOVEDADES_INICIALES: NovedadInstitucional[] = [
  {
    id: 'nov-01',
    titulo: 'Lanzamiento de la Plataforma Digital y Carnet Digital',
    bajada: 'La Biblioteca del Club Sportivo y Biblioteca Dr. Lautaro Roncedo da un paso histórico hacia el futuro con su nueva plataforma web progresiva.',
    contenido: 'Con inmensa alegría ponemos a disposición de todos nuestros socios y la comunidad de Alcira Gigena esta nueva herramienta digital que permitirá consultar libros, acceder a actas históricas, participar de actividades culturales y llevar el carnet social en el teléfono.',
    fecha: '2026-04-07',
    categoria: 'Institucional',
    destacado: true,
  },
  {
    id: 'nov-02',
    titulo: 'Digitalización del Archivo Histórico de Actas y Fotografías',
    bajada: 'Iniciamos el rescate y preservación de documentos fundacionales de nuestra querida institución y del pueblo.',
    contenido: 'Un equipo de colaboradores se encuentra trabajando en la digitalización sistemática de libros de actas y fotografías históricas aportadas por familias de Alcira Gigena. Muy pronto podrás buscar acontecimientos y antepasados desde tu celular.',
    fecha: '2026-04-05',
    categoria: 'Archivo',
    destacado: false,
  },
  {
    id: 'nov-03',
    titulo: 'Nuevas incorporaciones al catálogo literario',
    bajada: 'Más de 40 títulos de literatura argentina, historia y narrativa infantil ya están disponibles.',
    contenido: 'Los socios con cuota al día ya pueden consultar la disponibilidad en biblioteca y reservar sus ejemplares favoritos para el fin de semana.',
    fecha: '2026-04-01',
    categoria: 'Libros',
    destacado: false,
  },
];
